/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPlanCapsDtoListApiOperationResultFromDiscriminatorValue, type PlanCapsDtoListApiOperationResult } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/plans
 */
export interface PlansRequestBuilder extends BaseRequestBuilder<PlansRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PlanCapsDtoListApiOperationResult>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PlanCapsDtoListApiOperationResult | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PlansRequestBuilderUriTemplate = "{+baseurl}/api/plans";
/**
 * Metadata for all the requests in the request builder.
 */
export const PlansRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PlansRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createPlanCapsDtoListApiOperationResultFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
