/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createSpaceDtoApiOperationResultFromDiscriminatorValue, createSpaceDtoListApiOperationResultFromDiscriminatorValue, serializeSpaceDto, serializeSpaceDtoApiOperationResult, type ProblemDetails, type SpaceDto, type SpaceDtoApiOperationResult, type SpaceDtoListApiOperationResult } from '../../models/index.js';
// @ts-ignore
import { SpacesItemRequestBuilderRequestsMetadata, type SpacesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/spaces
 */
export interface SpacesRequestBuilder extends BaseRequestBuilder<SpacesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.spaces.item collection
     * @param id Unique identifier of the item
     * @returns {SpacesItemRequestBuilder}
     */
     byId(id: string) : SpacesItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SpaceDtoListApiOperationResult>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SpaceDtoListApiOperationResult | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SpaceDtoApiOperationResult>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 413 status code
     */
     post(body: SpaceDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SpaceDtoApiOperationResult | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SpaceDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SpacesRequestBuilderUriTemplate = "{+baseurl}/api/spaces";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SpacesRequestBuilderNavigationMetadata: Record<Exclude<keyof SpacesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: SpacesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SpacesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SpacesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createSpaceDtoListApiOperationResultFromDiscriminatorValue,
    },
    post: {
        uriTemplate: SpacesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            413: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSpaceDtoApiOperationResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSpaceDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
