/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AccountRequestBuilderNavigationMetadata, AccountRequestBuilderRequestsMetadata, type AccountRequestBuilder } from './account/index.js';
// @ts-ignore
import { AuthRequestBuilderNavigationMetadata, type AuthRequestBuilder } from './auth/index.js';
// @ts-ignore
import { BillingRequestBuilderNavigationMetadata, type BillingRequestBuilder } from './billing/index.js';
// @ts-ignore
import { SpacesRequestBuilderNavigationMetadata, SpacesRequestBuilderRequestsMetadata, type SpacesRequestBuilder } from './spaces/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The account property
     */
    get account(): AccountRequestBuilder;
    /**
     * The auth property
     */
    get auth(): AuthRequestBuilder;
    /**
     * The billing property
     */
    get billing(): BillingRequestBuilder;
    /**
     * The spaces property
     */
    get spaces(): SpacesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    account: {
        requestsMetadata: AccountRequestBuilderRequestsMetadata,
        navigationMetadata: AccountRequestBuilderNavigationMetadata,
    },
    auth: {
        navigationMetadata: AuthRequestBuilderNavigationMetadata,
    },
    billing: {
        navigationMetadata: BillingRequestBuilderNavigationMetadata,
    },
    spaces: {
        requestsMetadata: SpacesRequestBuilderRequestsMetadata,
        navigationMetadata: SpacesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
