/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AccountDto extends Parsable {
    /**
     * The email property
     */
    email: string;
    /**
     * The name property
     */
    name: string;
    /**
     * The plan property
     */
    plan: string;
    /**
     * The syncOn property
     */
    syncOn: boolean;
    /**
     * The usage property
     */
    usage: UsageDto;
}
export interface AccountDtoApiOperationResult extends Parsable {
    /**
     * The data property
     */
    data: AccountDto;
    /**
     * The errors property
     */
    errors: AccountDtoApiOperationResult_errors;
    /**
     * The isSuccess property
     */
    isSuccess: boolean;
}
export interface AccountDtoApiOperationResult_errors extends AdditionalDataHolder, Parsable {
}
export interface AuthResponse extends Parsable {
    /**
     * The accessToken property
     */
    accessToken: string;
    /**
     * The expiresIn property
     */
    expiresIn: number;
    /**
     * The refreshToken property
     */
    refreshToken: string;
    /**
     * The user property
     */
    user: AuthUserDto;
}
export interface AuthResponseApiOperationResult extends Parsable {
    /**
     * The data property
     */
    data: AuthResponse;
    /**
     * The errors property
     */
    errors: AuthResponseApiOperationResult_errors;
    /**
     * The isSuccess property
     */
    isSuccess: boolean;
}
export interface AuthResponseApiOperationResult_errors extends AdditionalDataHolder, Parsable {
}
export interface AuthUserDto extends Parsable {
    /**
     * The email property
     */
    email: string;
    /**
     * The name property
     */
    name: string;
    /**
     * The plan property
     */
    plan: string;
    /**
     * The syncOn property
     */
    syncOn: boolean;
}
export interface ChangePlanCommand extends Parsable {
    /**
     * The plan property
     */
    plan?: string | null;
}
export interface ChangePlanResult extends Parsable {
    /**
     * The account property
     */
    account: AccountDto;
    /**
     * The cancellationScheduled property
     */
    cancellationScheduled: boolean;
    /**
     * The checkoutUrl property
     */
    checkoutUrl?: string | null;
    /**
     * The proAccessUntil property
     */
    proAccessUntil?: Date | null;
}
export interface ChangePlanResultApiOperationResult extends Parsable {
    /**
     * The data property
     */
    data: ChangePlanResult;
    /**
     * The errors property
     */
    errors: ChangePlanResultApiOperationResult_errors;
    /**
     * The isSuccess property
     */
    isSuccess: boolean;
}
export interface ChangePlanResultApiOperationResult_errors extends AdditionalDataHolder, Parsable {
}
export interface ConsumeMagicLinkCommand extends Parsable {
    /**
     * The token property
     */
    token?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AccountDtoApiOperationResult_errors}
 */
// @ts-ignore
export function createAccountDtoApiOperationResult_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAccountDtoApiOperationResult_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AccountDtoApiOperationResult}
 */
// @ts-ignore
export function createAccountDtoApiOperationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAccountDtoApiOperationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AccountDto}
 */
// @ts-ignore
export function createAccountDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAccountDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuthResponseApiOperationResult_errors}
 */
// @ts-ignore
export function createAuthResponseApiOperationResult_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAuthResponseApiOperationResult_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuthResponseApiOperationResult}
 */
// @ts-ignore
export function createAuthResponseApiOperationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAuthResponseApiOperationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuthResponse}
 */
// @ts-ignore
export function createAuthResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAuthResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuthUserDto}
 */
// @ts-ignore
export function createAuthUserDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAuthUserDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ChangePlanCommand}
 */
// @ts-ignore
export function createChangePlanCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoChangePlanCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ChangePlanResultApiOperationResult_errors}
 */
// @ts-ignore
export function createChangePlanResultApiOperationResult_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoChangePlanResultApiOperationResult_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ChangePlanResultApiOperationResult}
 */
// @ts-ignore
export function createChangePlanResultApiOperationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoChangePlanResultApiOperationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ChangePlanResult}
 */
// @ts-ignore
export function createChangePlanResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoChangePlanResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ConsumeMagicLinkCommand}
 */
// @ts-ignore
export function createConsumeMagicLinkCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoConsumeMagicLinkCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemDtoApiOperationResult_errors}
 */
// @ts-ignore
export function createItemDtoApiOperationResult_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoItemDtoApiOperationResult_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemDtoApiOperationResult}
 */
// @ts-ignore
export function createItemDtoApiOperationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoItemDtoApiOperationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemDto}
 */
// @ts-ignore
export function createItemDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoItemDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PlanCapsDto}
 */
// @ts-ignore
export function createPlanCapsDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPlanCapsDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PlanCapsDtoListApiOperationResult_errors}
 */
// @ts-ignore
export function createPlanCapsDtoListApiOperationResult_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPlanCapsDtoListApiOperationResult_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PlanCapsDtoListApiOperationResult}
 */
// @ts-ignore
export function createPlanCapsDtoListApiOperationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPlanCapsDtoListApiOperationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProblemDetails}
 */
// @ts-ignore
export function createProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RectDto}
 */
// @ts-ignore
export function createRectDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRectDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RefreshTokenCommand}
 */
// @ts-ignore
export function createRefreshTokenCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRefreshTokenCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RequestMagicLinkCommand}
 */
// @ts-ignore
export function createRequestMagicLinkCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRequestMagicLinkCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RequestMagicLinkResultApiOperationResult_errors}
 */
// @ts-ignore
export function createRequestMagicLinkResultApiOperationResult_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRequestMagicLinkResultApiOperationResult_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RequestMagicLinkResultApiOperationResult}
 */
// @ts-ignore
export function createRequestMagicLinkResultApiOperationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRequestMagicLinkResultApiOperationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RequestMagicLinkResult}
 */
// @ts-ignore
export function createRequestMagicLinkResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRequestMagicLinkResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SetSyncCommand}
 */
// @ts-ignore
export function createSetSyncCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSetSyncCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SpaceDtoApiOperationResult_errors}
 */
// @ts-ignore
export function createSpaceDtoApiOperationResult_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSpaceDtoApiOperationResult_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SpaceDtoApiOperationResult}
 */
// @ts-ignore
export function createSpaceDtoApiOperationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSpaceDtoApiOperationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SpaceDto}
 */
// @ts-ignore
export function createSpaceDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSpaceDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SpaceDtoListApiOperationResult_errors}
 */
// @ts-ignore
export function createSpaceDtoListApiOperationResult_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSpaceDtoListApiOperationResult_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SpaceDtoListApiOperationResult}
 */
// @ts-ignore
export function createSpaceDtoListApiOperationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSpaceDtoListApiOperationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SpaceFieldsDtoApiOperationResult_errors}
 */
// @ts-ignore
export function createSpaceFieldsDtoApiOperationResult_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSpaceFieldsDtoApiOperationResult_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SpaceFieldsDtoApiOperationResult}
 */
// @ts-ignore
export function createSpaceFieldsDtoApiOperationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSpaceFieldsDtoApiOperationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SpaceFieldsDto}
 */
// @ts-ignore
export function createSpaceFieldsDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSpaceFieldsDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UsageDto}
 */
// @ts-ignore
export function createUsageDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUsageDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ZoneDtoApiOperationResult_errors}
 */
// @ts-ignore
export function createZoneDtoApiOperationResult_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoZoneDtoApiOperationResult_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ZoneDtoApiOperationResult}
 */
// @ts-ignore
export function createZoneDtoApiOperationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoZoneDtoApiOperationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ZoneDto}
 */
// @ts-ignore
export function createZoneDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoZoneDto;
}
/**
 * The deserialization information for the current model
 * @param AccountDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAccountDto(accountDto: Partial<AccountDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { accountDto.email = n.getStringValue(); },
        "name": n => { accountDto.name = n.getStringValue(); },
        "plan": n => { accountDto.plan = n.getStringValue(); },
        "syncOn": n => { accountDto.syncOn = n.getBooleanValue(); },
        "usage": n => { accountDto.usage = n.getObjectValue<UsageDto>(createUsageDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param AccountDtoApiOperationResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAccountDtoApiOperationResult(accountDtoApiOperationResult: Partial<AccountDtoApiOperationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { accountDtoApiOperationResult.data = n.getObjectValue<AccountDto>(createAccountDtoFromDiscriminatorValue); },
        "errors": n => { accountDtoApiOperationResult.errors = n.getObjectValue<AccountDtoApiOperationResult_errors>(createAccountDtoApiOperationResult_errorsFromDiscriminatorValue); },
        "isSuccess": n => { accountDtoApiOperationResult.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AccountDtoApiOperationResult_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAccountDtoApiOperationResult_errors(accountDtoApiOperationResult_errors: Partial<AccountDtoApiOperationResult_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param AuthResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuthResponse(authResponse: Partial<AuthResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "accessToken": n => { authResponse.accessToken = n.getStringValue(); },
        "expiresIn": n => { authResponse.expiresIn = n.getNumberValue(); },
        "refreshToken": n => { authResponse.refreshToken = n.getStringValue(); },
        "user": n => { authResponse.user = n.getObjectValue<AuthUserDto>(createAuthUserDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param AuthResponseApiOperationResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuthResponseApiOperationResult(authResponseApiOperationResult: Partial<AuthResponseApiOperationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { authResponseApiOperationResult.data = n.getObjectValue<AuthResponse>(createAuthResponseFromDiscriminatorValue); },
        "errors": n => { authResponseApiOperationResult.errors = n.getObjectValue<AuthResponseApiOperationResult_errors>(createAuthResponseApiOperationResult_errorsFromDiscriminatorValue); },
        "isSuccess": n => { authResponseApiOperationResult.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AuthResponseApiOperationResult_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuthResponseApiOperationResult_errors(authResponseApiOperationResult_errors: Partial<AuthResponseApiOperationResult_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param AuthUserDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuthUserDto(authUserDto: Partial<AuthUserDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { authUserDto.email = n.getStringValue(); },
        "name": n => { authUserDto.name = n.getStringValue(); },
        "plan": n => { authUserDto.plan = n.getStringValue(); },
        "syncOn": n => { authUserDto.syncOn = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ChangePlanCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoChangePlanCommand(changePlanCommand: Partial<ChangePlanCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "plan": n => { changePlanCommand.plan = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ChangePlanResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoChangePlanResult(changePlanResult: Partial<ChangePlanResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "account": n => { changePlanResult.account = n.getObjectValue<AccountDto>(createAccountDtoFromDiscriminatorValue); },
        "cancellationScheduled": n => { changePlanResult.cancellationScheduled = n.getBooleanValue(); },
        "checkoutUrl": n => { changePlanResult.checkoutUrl = n.getStringValue(); },
        "proAccessUntil": n => { changePlanResult.proAccessUntil = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ChangePlanResultApiOperationResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoChangePlanResultApiOperationResult(changePlanResultApiOperationResult: Partial<ChangePlanResultApiOperationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { changePlanResultApiOperationResult.data = n.getObjectValue<ChangePlanResult>(createChangePlanResultFromDiscriminatorValue); },
        "errors": n => { changePlanResultApiOperationResult.errors = n.getObjectValue<ChangePlanResultApiOperationResult_errors>(createChangePlanResultApiOperationResult_errorsFromDiscriminatorValue); },
        "isSuccess": n => { changePlanResultApiOperationResult.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ChangePlanResultApiOperationResult_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoChangePlanResultApiOperationResult_errors(changePlanResultApiOperationResult_errors: Partial<ChangePlanResultApiOperationResult_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param ConsumeMagicLinkCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoConsumeMagicLinkCommand(consumeMagicLinkCommand: Partial<ConsumeMagicLinkCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "token": n => { consumeMagicLinkCommand.token = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ItemDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemDto(itemDto: Partial<ItemDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "dateAdded": n => { itemDto.dateAdded = n.getStringValue(); },
        "depth": n => { itemDto.depth = n.getStringValue(); },
        "expiry": n => { itemDto.expiry = n.getStringValue(); },
        "icon": n => { itemDto.icon = n.getStringValue(); },
        "id": n => { itemDto.id = n.getStringValue(); },
        "level": n => { itemDto.level = n.getNumberValue(); },
        "name": n => { itemDto.name = n.getStringValue(); },
        "photo": n => { itemDto.photo = n.getStringValue(); },
        "quantity": n => { itemDto.quantity = n.getNumberValue(); },
        "slotIndex": n => { itemDto.slotIndex = n.getNumberValue(); },
        "tags": n => { itemDto.tags = n.getCollectionOfPrimitiveValues<string>("string"); },
        "zoneId": n => { itemDto.zoneId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ItemDtoApiOperationResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemDtoApiOperationResult(itemDtoApiOperationResult: Partial<ItemDtoApiOperationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { itemDtoApiOperationResult.data = n.getObjectValue<ItemDto>(createItemDtoFromDiscriminatorValue); },
        "errors": n => { itemDtoApiOperationResult.errors = n.getObjectValue<ItemDtoApiOperationResult_errors>(createItemDtoApiOperationResult_errorsFromDiscriminatorValue); },
        "isSuccess": n => { itemDtoApiOperationResult.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ItemDtoApiOperationResult_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemDtoApiOperationResult_errors(itemDtoApiOperationResult_errors: Partial<ItemDtoApiOperationResult_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param PlanCapsDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPlanCapsDto(planCapsDto: Partial<PlanCapsDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "items": n => { planCapsDto.items = n.getNumberValue(); },
        "photos": n => { planCapsDto.photos = n.getBooleanValue(); },
        "plan": n => { planCapsDto.plan = n.getStringValue(); },
        "spaces": n => { planCapsDto.spaces = n.getNumberValue(); },
        "sync": n => { planCapsDto.sync = n.getBooleanValue(); },
        "zones": n => { planCapsDto.zones = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PlanCapsDtoListApiOperationResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPlanCapsDtoListApiOperationResult(planCapsDtoListApiOperationResult: Partial<PlanCapsDtoListApiOperationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { planCapsDtoListApiOperationResult.data = n.getCollectionOfObjectValues<PlanCapsDto>(createPlanCapsDtoFromDiscriminatorValue); },
        "errors": n => { planCapsDtoListApiOperationResult.errors = n.getObjectValue<PlanCapsDtoListApiOperationResult_errors>(createPlanCapsDtoListApiOperationResult_errorsFromDiscriminatorValue); },
        "isSuccess": n => { planCapsDtoListApiOperationResult.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PlanCapsDtoListApiOperationResult_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPlanCapsDtoListApiOperationResult_errors(planCapsDtoListApiOperationResult_errors: Partial<PlanCapsDtoListApiOperationResult_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param ProblemDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProblemDetails(problemDetails: Partial<ProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { problemDetails.detail = n.getStringValue(); },
        "instance": n => { problemDetails.instance = n.getStringValue(); },
        "status": n => { problemDetails.status = n.getNumberValue(); },
        "title": n => { problemDetails.title = n.getStringValue(); },
        "type": n => { problemDetails.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RectDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRectDto(rectDto: Partial<RectDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "h": n => { rectDto.h = n.getNumberValue(); },
        "w": n => { rectDto.w = n.getNumberValue(); },
        "x": n => { rectDto.x = n.getNumberValue(); },
        "y": n => { rectDto.y = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RefreshTokenCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRefreshTokenCommand(refreshTokenCommand: Partial<RefreshTokenCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "refreshToken": n => { refreshTokenCommand.refreshToken = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RequestMagicLinkCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRequestMagicLinkCommand(requestMagicLinkCommand: Partial<RequestMagicLinkCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { requestMagicLinkCommand.email = n.getStringValue(); },
        "returnUrl": n => { requestMagicLinkCommand.returnUrl = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RequestMagicLinkResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRequestMagicLinkResult(requestMagicLinkResult: Partial<RequestMagicLinkResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "devLink": n => { requestMagicLinkResult.devLink = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RequestMagicLinkResultApiOperationResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRequestMagicLinkResultApiOperationResult(requestMagicLinkResultApiOperationResult: Partial<RequestMagicLinkResultApiOperationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { requestMagicLinkResultApiOperationResult.data = n.getObjectValue<RequestMagicLinkResult>(createRequestMagicLinkResultFromDiscriminatorValue); },
        "errors": n => { requestMagicLinkResultApiOperationResult.errors = n.getObjectValue<RequestMagicLinkResultApiOperationResult_errors>(createRequestMagicLinkResultApiOperationResult_errorsFromDiscriminatorValue); },
        "isSuccess": n => { requestMagicLinkResultApiOperationResult.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RequestMagicLinkResultApiOperationResult_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRequestMagicLinkResultApiOperationResult_errors(requestMagicLinkResultApiOperationResult_errors: Partial<RequestMagicLinkResultApiOperationResult_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param SetSyncCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSetSyncCommand(setSyncCommand: Partial<SetSyncCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "syncOn": n => { setSyncCommand.syncOn = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SpaceDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSpaceDto(spaceDto: Partial<SpaceDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "canvasMode": n => { spaceDto.canvasMode = n.getStringValue(); },
        "columnLabels": n => { spaceDto.columnLabels = n.getCollectionOfPrimitiveValues<string>("string"); },
        "id": n => { spaceDto.id = n.getStringValue(); },
        "items": n => { spaceDto.items = n.getCollectionOfObjectValues<ItemDto>(createItemDtoFromDiscriminatorValue); },
        "layoutColumns": n => { spaceDto.layoutColumns = n.getNumberValue(); },
        "name": n => { spaceDto.name = n.getStringValue(); },
        "type": n => { spaceDto.type = n.getStringValue(); },
        "viewMode": n => { spaceDto.viewMode = n.getStringValue(); },
        "zones": n => { spaceDto.zones = n.getCollectionOfObjectValues<ZoneDto>(createZoneDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param SpaceDtoApiOperationResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSpaceDtoApiOperationResult(spaceDtoApiOperationResult: Partial<SpaceDtoApiOperationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { spaceDtoApiOperationResult.data = n.getObjectValue<SpaceDto>(createSpaceDtoFromDiscriminatorValue); },
        "errors": n => { spaceDtoApiOperationResult.errors = n.getObjectValue<SpaceDtoApiOperationResult_errors>(createSpaceDtoApiOperationResult_errorsFromDiscriminatorValue); },
        "isSuccess": n => { spaceDtoApiOperationResult.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SpaceDtoApiOperationResult_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSpaceDtoApiOperationResult_errors(spaceDtoApiOperationResult_errors: Partial<SpaceDtoApiOperationResult_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param SpaceDtoListApiOperationResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSpaceDtoListApiOperationResult(spaceDtoListApiOperationResult: Partial<SpaceDtoListApiOperationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { spaceDtoListApiOperationResult.data = n.getCollectionOfObjectValues<SpaceDto>(createSpaceDtoFromDiscriminatorValue); },
        "errors": n => { spaceDtoListApiOperationResult.errors = n.getObjectValue<SpaceDtoListApiOperationResult_errors>(createSpaceDtoListApiOperationResult_errorsFromDiscriminatorValue); },
        "isSuccess": n => { spaceDtoListApiOperationResult.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SpaceDtoListApiOperationResult_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSpaceDtoListApiOperationResult_errors(spaceDtoListApiOperationResult_errors: Partial<SpaceDtoListApiOperationResult_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param SpaceFieldsDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSpaceFieldsDto(spaceFieldsDto: Partial<SpaceFieldsDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "canvasMode": n => { spaceFieldsDto.canvasMode = n.getStringValue(); },
        "columnLabels": n => { spaceFieldsDto.columnLabels = n.getCollectionOfPrimitiveValues<string>("string"); },
        "layoutColumns": n => { spaceFieldsDto.layoutColumns = n.getNumberValue(); },
        "name": n => { spaceFieldsDto.name = n.getStringValue(); },
        "type": n => { spaceFieldsDto.type = n.getStringValue(); },
        "viewMode": n => { spaceFieldsDto.viewMode = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SpaceFieldsDtoApiOperationResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSpaceFieldsDtoApiOperationResult(spaceFieldsDtoApiOperationResult: Partial<SpaceFieldsDtoApiOperationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { spaceFieldsDtoApiOperationResult.data = n.getObjectValue<SpaceFieldsDto>(createSpaceFieldsDtoFromDiscriminatorValue); },
        "errors": n => { spaceFieldsDtoApiOperationResult.errors = n.getObjectValue<SpaceFieldsDtoApiOperationResult_errors>(createSpaceFieldsDtoApiOperationResult_errorsFromDiscriminatorValue); },
        "isSuccess": n => { spaceFieldsDtoApiOperationResult.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SpaceFieldsDtoApiOperationResult_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSpaceFieldsDtoApiOperationResult_errors(spaceFieldsDtoApiOperationResult_errors: Partial<SpaceFieldsDtoApiOperationResult_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param UsageDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUsageDto(usageDto: Partial<UsageDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "fullestSpace": n => { usageDto.fullestSpace = n.getNumberValue(); },
        "items": n => { usageDto.items = n.getNumberValue(); },
        "spaces": n => { usageDto.spaces = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ZoneDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoZoneDto(zoneDto: Partial<ZoneDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "color": n => { zoneDto.color = n.getStringValue(); },
        "column": n => { zoneDto.column = n.getNumberValue(); },
        "facing": n => { zoneDto.facing = n.getStringValue(); },
        "floor": n => { zoneDto.floor = n.getBooleanValue(); },
        "gridCols": n => { zoneDto.gridCols = n.getNumberValue(); },
        "gridRows": n => { zoneDto.gridRows = n.getNumberValue(); },
        "hasDepth": n => { zoneDto.hasDepth = n.getBooleanValue(); },
        "id": n => { zoneDto.id = n.getStringValue(); },
        "kind": n => { zoneDto.kind = n.getStringValue(); },
        "label": n => { zoneDto.label = n.getStringValue(); },
        "levels": n => { zoneDto.levels = n.getNumberValue(); },
        "position": n => { zoneDto.position = n.getNumberValue(); },
        "rect": n => { zoneDto.rect = n.getObjectValue<RectDto>(createRectDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param ZoneDtoApiOperationResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoZoneDtoApiOperationResult(zoneDtoApiOperationResult: Partial<ZoneDtoApiOperationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { zoneDtoApiOperationResult.data = n.getObjectValue<ZoneDto>(createZoneDtoFromDiscriminatorValue); },
        "errors": n => { zoneDtoApiOperationResult.errors = n.getObjectValue<ZoneDtoApiOperationResult_errors>(createZoneDtoApiOperationResult_errorsFromDiscriminatorValue); },
        "isSuccess": n => { zoneDtoApiOperationResult.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ZoneDtoApiOperationResult_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoZoneDtoApiOperationResult_errors(zoneDtoApiOperationResult_errors: Partial<ZoneDtoApiOperationResult_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
export interface ItemDto extends Parsable {
    /**
     * The dateAdded property
     */
    dateAdded: string;
    /**
     * The depth property
     */
    depth: string;
    /**
     * The expiry property
     */
    expiry?: string | null;
    /**
     * The icon property
     */
    icon?: string | null;
    /**
     * The id property
     */
    id: string;
    /**
     * The level property
     */
    level: number;
    /**
     * The name property
     */
    name: string;
    /**
     * The photo property
     */
    photo?: string | null;
    /**
     * The quantity property
     */
    quantity: number;
    /**
     * The slotIndex property
     */
    slotIndex?: number | null;
    /**
     * The tags property
     */
    tags: string[];
    /**
     * The zoneId property
     */
    zoneId: string;
}
export interface ItemDtoApiOperationResult extends Parsable {
    /**
     * The data property
     */
    data: ItemDto;
    /**
     * The errors property
     */
    errors: ItemDtoApiOperationResult_errors;
    /**
     * The isSuccess property
     */
    isSuccess: boolean;
}
export interface ItemDtoApiOperationResult_errors extends AdditionalDataHolder, Parsable {
}
export interface PlanCapsDto extends Parsable {
    /**
     * The items property
     */
    items?: number | null;
    /**
     * The photos property
     */
    photos: boolean;
    /**
     * The plan property
     */
    plan: string;
    /**
     * The spaces property
     */
    spaces?: number | null;
    /**
     * The sync property
     */
    sync: boolean;
    /**
     * The zones property
     */
    zones?: number | null;
}
export interface PlanCapsDtoListApiOperationResult extends Parsable {
    /**
     * The data property
     */
    data?: PlanCapsDto[] | null;
    /**
     * The errors property
     */
    errors: PlanCapsDtoListApiOperationResult_errors;
    /**
     * The isSuccess property
     */
    isSuccess: boolean;
}
export interface PlanCapsDtoListApiOperationResult_errors extends AdditionalDataHolder, Parsable {
}
export interface ProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface RectDto extends Parsable {
    /**
     * The h property
     */
    h: number;
    /**
     * The w property
     */
    w: number;
    /**
     * The x property
     */
    x: number;
    /**
     * The y property
     */
    y: number;
}
export interface RefreshTokenCommand extends Parsable {
    /**
     * The refreshToken property
     */
    refreshToken?: string | null;
}
export interface RequestMagicLinkCommand extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The returnUrl property
     */
    returnUrl?: string | null;
}
export interface RequestMagicLinkResult extends Parsable {
    /**
     * The devLink property
     */
    devLink?: string | null;
}
export interface RequestMagicLinkResultApiOperationResult extends Parsable {
    /**
     * The data property
     */
    data: RequestMagicLinkResult;
    /**
     * The errors property
     */
    errors: RequestMagicLinkResultApiOperationResult_errors;
    /**
     * The isSuccess property
     */
    isSuccess: boolean;
}
export interface RequestMagicLinkResultApiOperationResult_errors extends AdditionalDataHolder, Parsable {
}
/**
 * Serializes information the current object
 * @param AccountDto The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAccountDto(writer: SerializationWriter, accountDto: Partial<AccountDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!accountDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", accountDto.email);
    writer.writeStringValue("name", accountDto.name);
    writer.writeStringValue("plan", accountDto.plan);
    writer.writeBooleanValue("syncOn", accountDto.syncOn);
    writer.writeObjectValue<UsageDto>("usage", accountDto.usage, serializeUsageDto);
}
/**
 * Serializes information the current object
 * @param AccountDtoApiOperationResult The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAccountDtoApiOperationResult(writer: SerializationWriter, accountDtoApiOperationResult: Partial<AccountDtoApiOperationResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!accountDtoApiOperationResult || isSerializingDerivedType) { return; }
    writer.writeObjectValue<AccountDto>("data", accountDtoApiOperationResult.data, serializeAccountDto);
    writer.writeObjectValue<AccountDtoApiOperationResult_errors>("errors", accountDtoApiOperationResult.errors, serializeAccountDtoApiOperationResult_errors);
    writer.writeBooleanValue("isSuccess", accountDtoApiOperationResult.isSuccess);
}
/**
 * Serializes information the current object
 * @param AccountDtoApiOperationResult_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAccountDtoApiOperationResult_errors(writer: SerializationWriter, accountDtoApiOperationResult_errors: Partial<AccountDtoApiOperationResult_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!accountDtoApiOperationResult_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(accountDtoApiOperationResult_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param AuthResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuthResponse(writer: SerializationWriter, authResponse: Partial<AuthResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!authResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("accessToken", authResponse.accessToken);
    writer.writeNumberValue("expiresIn", authResponse.expiresIn);
    writer.writeStringValue("refreshToken", authResponse.refreshToken);
    writer.writeObjectValue<AuthUserDto>("user", authResponse.user, serializeAuthUserDto);
}
/**
 * Serializes information the current object
 * @param AuthResponseApiOperationResult The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuthResponseApiOperationResult(writer: SerializationWriter, authResponseApiOperationResult: Partial<AuthResponseApiOperationResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!authResponseApiOperationResult || isSerializingDerivedType) { return; }
    writer.writeObjectValue<AuthResponse>("data", authResponseApiOperationResult.data, serializeAuthResponse);
    writer.writeObjectValue<AuthResponseApiOperationResult_errors>("errors", authResponseApiOperationResult.errors, serializeAuthResponseApiOperationResult_errors);
    writer.writeBooleanValue("isSuccess", authResponseApiOperationResult.isSuccess);
}
/**
 * Serializes information the current object
 * @param AuthResponseApiOperationResult_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuthResponseApiOperationResult_errors(writer: SerializationWriter, authResponseApiOperationResult_errors: Partial<AuthResponseApiOperationResult_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!authResponseApiOperationResult_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(authResponseApiOperationResult_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param AuthUserDto The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuthUserDto(writer: SerializationWriter, authUserDto: Partial<AuthUserDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!authUserDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", authUserDto.email);
    writer.writeStringValue("name", authUserDto.name);
    writer.writeStringValue("plan", authUserDto.plan);
    writer.writeBooleanValue("syncOn", authUserDto.syncOn);
}
/**
 * Serializes information the current object
 * @param ChangePlanCommand The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeChangePlanCommand(writer: SerializationWriter, changePlanCommand: Partial<ChangePlanCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!changePlanCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("plan", changePlanCommand.plan);
}
/**
 * Serializes information the current object
 * @param ChangePlanResult The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeChangePlanResult(writer: SerializationWriter, changePlanResult: Partial<ChangePlanResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!changePlanResult || isSerializingDerivedType) { return; }
    writer.writeObjectValue<AccountDto>("account", changePlanResult.account, serializeAccountDto);
    writer.writeBooleanValue("cancellationScheduled", changePlanResult.cancellationScheduled);
    writer.writeStringValue("checkoutUrl", changePlanResult.checkoutUrl);
    writer.writeDateValue("proAccessUntil", changePlanResult.proAccessUntil);
}
/**
 * Serializes information the current object
 * @param ChangePlanResultApiOperationResult The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeChangePlanResultApiOperationResult(writer: SerializationWriter, changePlanResultApiOperationResult: Partial<ChangePlanResultApiOperationResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!changePlanResultApiOperationResult || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ChangePlanResult>("data", changePlanResultApiOperationResult.data, serializeChangePlanResult);
    writer.writeObjectValue<ChangePlanResultApiOperationResult_errors>("errors", changePlanResultApiOperationResult.errors, serializeChangePlanResultApiOperationResult_errors);
    writer.writeBooleanValue("isSuccess", changePlanResultApiOperationResult.isSuccess);
}
/**
 * Serializes information the current object
 * @param ChangePlanResultApiOperationResult_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeChangePlanResultApiOperationResult_errors(writer: SerializationWriter, changePlanResultApiOperationResult_errors: Partial<ChangePlanResultApiOperationResult_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!changePlanResultApiOperationResult_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(changePlanResultApiOperationResult_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param ConsumeMagicLinkCommand The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeConsumeMagicLinkCommand(writer: SerializationWriter, consumeMagicLinkCommand: Partial<ConsumeMagicLinkCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!consumeMagicLinkCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("token", consumeMagicLinkCommand.token);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ItemDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemDto(writer: SerializationWriter, itemDto: Partial<ItemDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!itemDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("dateAdded", itemDto.dateAdded);
    writer.writeStringValue("depth", itemDto.depth);
    writer.writeStringValue("expiry", itemDto.expiry);
    writer.writeStringValue("icon", itemDto.icon);
    writer.writeStringValue("id", itemDto.id);
    writer.writeNumberValue("level", itemDto.level);
    writer.writeStringValue("name", itemDto.name);
    writer.writeStringValue("photo", itemDto.photo);
    writer.writeNumberValue("quantity", itemDto.quantity);
    writer.writeNumberValue("slotIndex", itemDto.slotIndex);
    writer.writeCollectionOfPrimitiveValues<string>("tags", itemDto.tags);
    writer.writeStringValue("zoneId", itemDto.zoneId);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ItemDtoApiOperationResult The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemDtoApiOperationResult(writer: SerializationWriter, itemDtoApiOperationResult: Partial<ItemDtoApiOperationResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!itemDtoApiOperationResult || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ItemDto>("data", itemDtoApiOperationResult.data, serializeItemDto);
    writer.writeObjectValue<ItemDtoApiOperationResult_errors>("errors", itemDtoApiOperationResult.errors, serializeItemDtoApiOperationResult_errors);
    writer.writeBooleanValue("isSuccess", itemDtoApiOperationResult.isSuccess);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ItemDtoApiOperationResult_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemDtoApiOperationResult_errors(writer: SerializationWriter, itemDtoApiOperationResult_errors: Partial<ItemDtoApiOperationResult_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!itemDtoApiOperationResult_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(itemDtoApiOperationResult_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PlanCapsDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePlanCapsDto(writer: SerializationWriter, planCapsDto: Partial<PlanCapsDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!planCapsDto || isSerializingDerivedType) { return; }
    writer.writeNumberValue("items", planCapsDto.items);
    writer.writeBooleanValue("photos", planCapsDto.photos);
    writer.writeStringValue("plan", planCapsDto.plan);
    writer.writeNumberValue("spaces", planCapsDto.spaces);
    writer.writeBooleanValue("sync", planCapsDto.sync);
    writer.writeNumberValue("zones", planCapsDto.zones);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PlanCapsDtoListApiOperationResult The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePlanCapsDtoListApiOperationResult(writer: SerializationWriter, planCapsDtoListApiOperationResult: Partial<PlanCapsDtoListApiOperationResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!planCapsDtoListApiOperationResult || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<PlanCapsDto>("data", planCapsDtoListApiOperationResult.data, serializePlanCapsDto);
    writer.writeObjectValue<PlanCapsDtoListApiOperationResult_errors>("errors", planCapsDtoListApiOperationResult.errors, serializePlanCapsDtoListApiOperationResult_errors);
    writer.writeBooleanValue("isSuccess", planCapsDtoListApiOperationResult.isSuccess);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PlanCapsDtoListApiOperationResult_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePlanCapsDtoListApiOperationResult_errors(writer: SerializationWriter, planCapsDtoListApiOperationResult_errors: Partial<PlanCapsDtoListApiOperationResult_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!planCapsDtoListApiOperationResult_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(planCapsDtoListApiOperationResult_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProblemDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProblemDetails(writer: SerializationWriter, problemDetails: Partial<ProblemDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!problemDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", problemDetails.detail);
    writer.writeStringValue("instance", problemDetails.instance);
    writer.writeNumberValue("status", problemDetails.status);
    writer.writeStringValue("title", problemDetails.title);
    writer.writeStringValue("type", problemDetails.type);
    writer.writeAdditionalData(problemDetails.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RectDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRectDto(writer: SerializationWriter, rectDto: Partial<RectDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!rectDto || isSerializingDerivedType) { return; }
    writer.writeNumberValue("h", rectDto.h);
    writer.writeNumberValue("w", rectDto.w);
    writer.writeNumberValue("x", rectDto.x);
    writer.writeNumberValue("y", rectDto.y);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RefreshTokenCommand The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRefreshTokenCommand(writer: SerializationWriter, refreshTokenCommand: Partial<RefreshTokenCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!refreshTokenCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("refreshToken", refreshTokenCommand.refreshToken);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RequestMagicLinkCommand The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRequestMagicLinkCommand(writer: SerializationWriter, requestMagicLinkCommand: Partial<RequestMagicLinkCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!requestMagicLinkCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", requestMagicLinkCommand.email);
    writer.writeStringValue("returnUrl", requestMagicLinkCommand.returnUrl);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RequestMagicLinkResult The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRequestMagicLinkResult(writer: SerializationWriter, requestMagicLinkResult: Partial<RequestMagicLinkResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!requestMagicLinkResult || isSerializingDerivedType) { return; }
    writer.writeStringValue("devLink", requestMagicLinkResult.devLink);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RequestMagicLinkResultApiOperationResult The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRequestMagicLinkResultApiOperationResult(writer: SerializationWriter, requestMagicLinkResultApiOperationResult: Partial<RequestMagicLinkResultApiOperationResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!requestMagicLinkResultApiOperationResult || isSerializingDerivedType) { return; }
    writer.writeObjectValue<RequestMagicLinkResult>("data", requestMagicLinkResultApiOperationResult.data, serializeRequestMagicLinkResult);
    writer.writeObjectValue<RequestMagicLinkResultApiOperationResult_errors>("errors", requestMagicLinkResultApiOperationResult.errors, serializeRequestMagicLinkResultApiOperationResult_errors);
    writer.writeBooleanValue("isSuccess", requestMagicLinkResultApiOperationResult.isSuccess);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RequestMagicLinkResultApiOperationResult_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRequestMagicLinkResultApiOperationResult_errors(writer: SerializationWriter, requestMagicLinkResultApiOperationResult_errors: Partial<RequestMagicLinkResultApiOperationResult_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!requestMagicLinkResultApiOperationResult_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(requestMagicLinkResultApiOperationResult_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SetSyncCommand The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSetSyncCommand(writer: SerializationWriter, setSyncCommand: Partial<SetSyncCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!setSyncCommand || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("syncOn", setSyncCommand.syncOn);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SpaceDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSpaceDto(writer: SerializationWriter, spaceDto: Partial<SpaceDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!spaceDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("canvasMode", spaceDto.canvasMode);
    writer.writeCollectionOfPrimitiveValues<string>("columnLabels", spaceDto.columnLabels);
    writer.writeStringValue("id", spaceDto.id);
    writer.writeCollectionOfObjectValues<ItemDto>("items", spaceDto.items, serializeItemDto);
    writer.writeNumberValue("layoutColumns", spaceDto.layoutColumns);
    writer.writeStringValue("name", spaceDto.name);
    writer.writeStringValue("type", spaceDto.type);
    writer.writeStringValue("viewMode", spaceDto.viewMode);
    writer.writeCollectionOfObjectValues<ZoneDto>("zones", spaceDto.zones, serializeZoneDto);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SpaceDtoApiOperationResult The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSpaceDtoApiOperationResult(writer: SerializationWriter, spaceDtoApiOperationResult: Partial<SpaceDtoApiOperationResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!spaceDtoApiOperationResult || isSerializingDerivedType) { return; }
    writer.writeObjectValue<SpaceDto>("data", spaceDtoApiOperationResult.data, serializeSpaceDto);
    writer.writeObjectValue<SpaceDtoApiOperationResult_errors>("errors", spaceDtoApiOperationResult.errors, serializeSpaceDtoApiOperationResult_errors);
    writer.writeBooleanValue("isSuccess", spaceDtoApiOperationResult.isSuccess);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SpaceDtoApiOperationResult_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSpaceDtoApiOperationResult_errors(writer: SerializationWriter, spaceDtoApiOperationResult_errors: Partial<SpaceDtoApiOperationResult_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!spaceDtoApiOperationResult_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(spaceDtoApiOperationResult_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SpaceDtoListApiOperationResult The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSpaceDtoListApiOperationResult(writer: SerializationWriter, spaceDtoListApiOperationResult: Partial<SpaceDtoListApiOperationResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!spaceDtoListApiOperationResult || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<SpaceDto>("data", spaceDtoListApiOperationResult.data, serializeSpaceDto);
    writer.writeObjectValue<SpaceDtoListApiOperationResult_errors>("errors", spaceDtoListApiOperationResult.errors, serializeSpaceDtoListApiOperationResult_errors);
    writer.writeBooleanValue("isSuccess", spaceDtoListApiOperationResult.isSuccess);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SpaceDtoListApiOperationResult_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSpaceDtoListApiOperationResult_errors(writer: SerializationWriter, spaceDtoListApiOperationResult_errors: Partial<SpaceDtoListApiOperationResult_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!spaceDtoListApiOperationResult_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(spaceDtoListApiOperationResult_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SpaceFieldsDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSpaceFieldsDto(writer: SerializationWriter, spaceFieldsDto: Partial<SpaceFieldsDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!spaceFieldsDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("canvasMode", spaceFieldsDto.canvasMode);
    writer.writeCollectionOfPrimitiveValues<string>("columnLabels", spaceFieldsDto.columnLabels);
    writer.writeNumberValue("layoutColumns", spaceFieldsDto.layoutColumns);
    writer.writeStringValue("name", spaceFieldsDto.name);
    writer.writeStringValue("type", spaceFieldsDto.type);
    writer.writeStringValue("viewMode", spaceFieldsDto.viewMode);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SpaceFieldsDtoApiOperationResult The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSpaceFieldsDtoApiOperationResult(writer: SerializationWriter, spaceFieldsDtoApiOperationResult: Partial<SpaceFieldsDtoApiOperationResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!spaceFieldsDtoApiOperationResult || isSerializingDerivedType) { return; }
    writer.writeObjectValue<SpaceFieldsDto>("data", spaceFieldsDtoApiOperationResult.data, serializeSpaceFieldsDto);
    writer.writeObjectValue<SpaceFieldsDtoApiOperationResult_errors>("errors", spaceFieldsDtoApiOperationResult.errors, serializeSpaceFieldsDtoApiOperationResult_errors);
    writer.writeBooleanValue("isSuccess", spaceFieldsDtoApiOperationResult.isSuccess);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SpaceFieldsDtoApiOperationResult_errors The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSpaceFieldsDtoApiOperationResult_errors(writer: SerializationWriter, spaceFieldsDtoApiOperationResult_errors: Partial<SpaceFieldsDtoApiOperationResult_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!spaceFieldsDtoApiOperationResult_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(spaceFieldsDtoApiOperationResult_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UsageDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUsageDto(writer: SerializationWriter, usageDto: Partial<UsageDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!usageDto || isSerializingDerivedType) { return; }
    writer.writeNumberValue("fullestSpace", usageDto.fullestSpace);
    writer.writeNumberValue("items", usageDto.items);
    writer.writeNumberValue("spaces", usageDto.spaces);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 * @param ZoneDto The instance to serialize from.
 */
// @ts-ignore
export function serializeZoneDto(writer: SerializationWriter, zoneDto: Partial<ZoneDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!zoneDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("color", zoneDto.color);
    writer.writeNumberValue("column", zoneDto.column);
    writer.writeStringValue("facing", zoneDto.facing);
    writer.writeBooleanValue("floor", zoneDto.floor);
    writer.writeNumberValue("gridCols", zoneDto.gridCols);
    writer.writeNumberValue("gridRows", zoneDto.gridRows);
    writer.writeBooleanValue("hasDepth", zoneDto.hasDepth);
    writer.writeStringValue("id", zoneDto.id);
    writer.writeStringValue("kind", zoneDto.kind);
    writer.writeStringValue("label", zoneDto.label);
    writer.writeNumberValue("levels", zoneDto.levels);
    writer.writeNumberValue("position", zoneDto.position);
    writer.writeObjectValue<RectDto>("rect", zoneDto.rect, serializeRectDto);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 * @param ZoneDtoApiOperationResult The instance to serialize from.
 */
// @ts-ignore
export function serializeZoneDtoApiOperationResult(writer: SerializationWriter, zoneDtoApiOperationResult: Partial<ZoneDtoApiOperationResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!zoneDtoApiOperationResult || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ZoneDto>("data", zoneDtoApiOperationResult.data, serializeZoneDto);
    writer.writeObjectValue<ZoneDtoApiOperationResult_errors>("errors", zoneDtoApiOperationResult.errors, serializeZoneDtoApiOperationResult_errors);
    writer.writeBooleanValue("isSuccess", zoneDtoApiOperationResult.isSuccess);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 * @param ZoneDtoApiOperationResult_errors The instance to serialize from.
 */
// @ts-ignore
export function serializeZoneDtoApiOperationResult_errors(writer: SerializationWriter, zoneDtoApiOperationResult_errors: Partial<ZoneDtoApiOperationResult_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!zoneDtoApiOperationResult_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(zoneDtoApiOperationResult_errors.additionalData);
}
export interface SetSyncCommand extends Parsable {
    /**
     * The syncOn property
     */
    syncOn?: boolean | null;
}
export interface SpaceDto extends Parsable {
    /**
     * The canvasMode property
     */
    canvasMode: string;
    /**
     * The columnLabels property
     */
    columnLabels?: string[] | null;
    /**
     * The id property
     */
    id: string;
    /**
     * The items property
     */
    items: ItemDto[];
    /**
     * The layoutColumns property
     */
    layoutColumns: number;
    /**
     * The name property
     */
    name: string;
    /**
     * The type property
     */
    type: string;
    /**
     * The viewMode property
     */
    viewMode: string;
    /**
     * The zones property
     */
    zones: ZoneDto[];
}
export interface SpaceDtoApiOperationResult extends Parsable {
    /**
     * The data property
     */
    data: SpaceDto;
    /**
     * The errors property
     */
    errors: SpaceDtoApiOperationResult_errors;
    /**
     * The isSuccess property
     */
    isSuccess: boolean;
}
export interface SpaceDtoApiOperationResult_errors extends AdditionalDataHolder, Parsable {
}
export interface SpaceDtoListApiOperationResult extends Parsable {
    /**
     * The data property
     */
    data?: SpaceDto[] | null;
    /**
     * The errors property
     */
    errors: SpaceDtoListApiOperationResult_errors;
    /**
     * The isSuccess property
     */
    isSuccess: boolean;
}
export interface SpaceDtoListApiOperationResult_errors extends AdditionalDataHolder, Parsable {
}
export interface SpaceFieldsDto extends Parsable {
    /**
     * The canvasMode property
     */
    canvasMode: string;
    /**
     * The columnLabels property
     */
    columnLabels?: string[] | null;
    /**
     * The layoutColumns property
     */
    layoutColumns: number;
    /**
     * The name property
     */
    name: string;
    /**
     * The type property
     */
    type: string;
    /**
     * The viewMode property
     */
    viewMode: string;
}
export interface SpaceFieldsDtoApiOperationResult extends Parsable {
    /**
     * The data property
     */
    data: SpaceFieldsDto;
    /**
     * The errors property
     */
    errors: SpaceFieldsDtoApiOperationResult_errors;
    /**
     * The isSuccess property
     */
    isSuccess: boolean;
}
export interface SpaceFieldsDtoApiOperationResult_errors extends AdditionalDataHolder, Parsable {
}
export interface UsageDto extends Parsable {
    /**
     * The fullestSpace property
     */
    fullestSpace: number;
    /**
     * The items property
     */
    items: number;
    /**
     * The spaces property
     */
    spaces: number;
}
export interface ZoneDto extends Parsable {
    /**
     * The color property
     */
    color: string;
    /**
     * The column property
     */
    column: number;
    /**
     * The facing property
     */
    facing: string;
    /**
     * The floor property
     */
    floor: boolean;
    /**
     * The gridCols property
     */
    gridCols: number;
    /**
     * The gridRows property
     */
    gridRows: number;
    /**
     * The hasDepth property
     */
    hasDepth: boolean;
    /**
     * The id property
     */
    id: string;
    /**
     * The kind property
     */
    kind: string;
    /**
     * The label property
     */
    label?: string | null;
    /**
     * The levels property
     */
    levels: number;
    /**
     * The position property
     */
    position: number;
    /**
     * The rect property
     */
    rect: RectDto;
}
export interface ZoneDtoApiOperationResult extends Parsable {
    /**
     * The data property
     */
    data: ZoneDto;
    /**
     * The errors property
     */
    errors: ZoneDtoApiOperationResult_errors;
    /**
     * The isSuccess property
     */
    isSuccess: boolean;
}
export interface ZoneDtoApiOperationResult_errors extends AdditionalDataHolder, Parsable {
}
/* tslint:enable */
/* eslint-enable */
