/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAccountDtoApiOperationResultFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeAccountDtoApiOperationResult, serializeSetSyncCommand, type AccountDtoApiOperationResult, type ProblemDetails, type SetSyncCommand } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/account/sync
 */
export interface SyncRequestBuilder extends BaseRequestBuilder<SyncRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AccountDtoApiOperationResult>}
     * @throws {ProblemDetails} error when the service returns a 403 status code
     */
     put(body: SetSyncCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AccountDtoApiOperationResult | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: SetSyncCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SyncRequestBuilderUriTemplate = "{+baseurl}/api/account/sync";
/**
 * Metadata for all the requests in the request builder.
 */
export const SyncRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: SyncRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAccountDtoApiOperationResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSetSyncCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
