/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createRequestMagicLinkResultApiOperationResultFromDiscriminatorValue, serializeRequestMagicLinkCommand, serializeRequestMagicLinkResultApiOperationResult, type ProblemDetails, type RequestMagicLinkCommand, type RequestMagicLinkResultApiOperationResult } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/auth/magic-link
 */
export interface MagicLinkRequestBuilder extends BaseRequestBuilder<MagicLinkRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RequestMagicLinkResultApiOperationResult>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     post(body: RequestMagicLinkCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RequestMagicLinkResultApiOperationResult | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RequestMagicLinkCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MagicLinkRequestBuilderUriTemplate = "{+baseurl}/api/auth/magic-link";
/**
 * Metadata for all the requests in the request builder.
 */
export const MagicLinkRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: MagicLinkRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRequestMagicLinkResultApiOperationResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRequestMagicLinkCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
