/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createSpaceReadDtoApiOperationResultFromDiscriminatorValue, type ProblemDetails, type SpaceReadDtoApiOperationResult } from '../../../models/index.js';
// @ts-ignore
import { FieldsRequestBuilderRequestsMetadata, type FieldsRequestBuilder } from './fields/index.js';
// @ts-ignore
import { ItemsRequestBuilderNavigationMetadata, ItemsRequestBuilderRequestsMetadata, type ItemsRequestBuilder } from './items/index.js';
// @ts-ignore
import { type ZonesRequestBuilder, ZonesRequestBuilderNavigationMetadata, ZonesRequestBuilderRequestsMetadata } from './zones/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/spaces/{id}
 */
export interface SpacesItemRequestBuilder extends BaseRequestBuilder<SpacesItemRequestBuilder> {
    /**
     * The fields property
     */
    get fields(): FieldsRequestBuilder;
    /**
     * The items property
     */
    get items(): ItemsRequestBuilder;
    /**
     * The zones property
     */
    get zones(): ZonesRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SpaceReadDtoApiOperationResult>}
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SpaceReadDtoApiOperationResult | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SpacesItemRequestBuilderUriTemplate = "{+baseurl}/api/spaces/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SpacesItemRequestBuilderNavigationMetadata: Record<Exclude<keyof SpacesItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    fields: {
        requestsMetadata: FieldsRequestBuilderRequestsMetadata,
    },
    items: {
        requestsMetadata: ItemsRequestBuilderRequestsMetadata,
        navigationMetadata: ItemsRequestBuilderNavigationMetadata,
    },
    zones: {
        requestsMetadata: ZonesRequestBuilderRequestsMetadata,
        navigationMetadata: ZonesRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SpacesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: SpacesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: SpacesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSpaceReadDtoApiOperationResultFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
