/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createZoneDtoApiOperationResultFromDiscriminatorValue, serializeZoneDto, serializeZoneDtoApiOperationResult, type ProblemDetails, type ZoneDto, type ZoneDtoApiOperationResult } from '../../../../models/index.js';
// @ts-ignore
import { type WithZoneItemRequestBuilder, WithZoneItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/spaces/{id}/zones
 */
export interface ZonesRequestBuilder extends BaseRequestBuilder<ZonesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.spaces.item.zones.item collection
     * @param zoneId Unique identifier of the item
     * @returns {WithZoneItemRequestBuilder}
     */
     byZoneId(zoneId: string) : WithZoneItemRequestBuilder;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ZoneDtoApiOperationResult>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     post(body: ZoneDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ZoneDtoApiOperationResult | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ZoneDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ZonesRequestBuilderUriTemplate = "{+baseurl}/api/spaces/{id}/zones";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ZonesRequestBuilderNavigationMetadata: Record<Exclude<keyof ZonesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byZoneId: {
        requestsMetadata: WithZoneItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["zoneId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ZonesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ZonesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createZoneDtoApiOperationResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeZoneDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
