/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WebhookRequestBuilder, WebhookRequestBuilderRequestsMetadata } from './webhook/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/billing
 */
export interface BillingRequestBuilder extends BaseRequestBuilder<BillingRequestBuilder> {
    /**
     * The webhook property
     */
    get webhook(): WebhookRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const BillingRequestBuilderUriTemplate = "{+baseurl}/api/billing";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BillingRequestBuilderNavigationMetadata: Record<Exclude<keyof BillingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    webhook: {
        requestsMetadata: WebhookRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
