/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAccountDtoApiOperationResultFromDiscriminatorValue, type AccountDtoApiOperationResult } from '../../models/index.js';
// @ts-ignore
import { PlanRequestBuilderRequestsMetadata, type PlanRequestBuilder } from './plan/index.js';
// @ts-ignore
import { SyncRequestBuilderRequestsMetadata, type SyncRequestBuilder } from './sync/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/account
 */
export interface AccountRequestBuilder extends BaseRequestBuilder<AccountRequestBuilder> {
    /**
     * The plan property
     */
    get plan(): PlanRequestBuilder;
    /**
     * The sync property
     */
    get sync(): SyncRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AccountDtoApiOperationResult>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AccountDtoApiOperationResult | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AccountRequestBuilderUriTemplate = "{+baseurl}/api/account";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AccountRequestBuilderNavigationMetadata: Record<Exclude<keyof AccountRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    plan: {
        requestsMetadata: PlanRequestBuilderRequestsMetadata,
    },
    sync: {
        requestsMetadata: SyncRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AccountRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AccountRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createAccountDtoApiOperationResultFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
