/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ConsumeRequestBuilderRequestsMetadata, type ConsumeRequestBuilder } from './consume/index.js';
// @ts-ignore
import { MagicLinkRequestBuilderRequestsMetadata, type MagicLinkRequestBuilder } from './magicLink/index.js';
// @ts-ignore
import { RefreshRequestBuilderRequestsMetadata, type RefreshRequestBuilder } from './refresh/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/auth
 */
export interface AuthRequestBuilder extends BaseRequestBuilder<AuthRequestBuilder> {
    /**
     * The consume property
     */
    get consume(): ConsumeRequestBuilder;
    /**
     * The magicLink property
     */
    get magicLink(): MagicLinkRequestBuilder;
    /**
     * The refresh property
     */
    get refresh(): RefreshRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AuthRequestBuilderUriTemplate = "{+baseurl}/api/auth";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AuthRequestBuilderNavigationMetadata: Record<Exclude<keyof AuthRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    consume: {
        requestsMetadata: ConsumeRequestBuilderRequestsMetadata,
    },
    magicLink: {
        requestsMetadata: MagicLinkRequestBuilderRequestsMetadata,
    },
    refresh: {
        requestsMetadata: RefreshRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
