/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createChangePlanResultApiOperationResultFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeChangePlanCommand, serializeChangePlanResultApiOperationResult, type ChangePlanCommand, type ChangePlanResultApiOperationResult, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/account/plan
 */
export interface PlanRequestBuilder extends BaseRequestBuilder<PlanRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ChangePlanResultApiOperationResult>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     put(body: ChangePlanCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ChangePlanResultApiOperationResult | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: ChangePlanCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PlanRequestBuilderUriTemplate = "{+baseurl}/api/account/plan";
/**
 * Metadata for all the requests in the request builder.
 */
export const PlanRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: PlanRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createChangePlanResultApiOperationResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeChangePlanCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
