/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createSpaceFieldsDtoApiOperationResultFromDiscriminatorValue, serializeSpaceFieldsDto, serializeSpaceFieldsDtoApiOperationResult, type ProblemDetails, type SpaceFieldsDto, type SpaceFieldsDtoApiOperationResult } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/spaces/{id}/fields
 */
export interface FieldsRequestBuilder extends BaseRequestBuilder<FieldsRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SpaceFieldsDtoApiOperationResult>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     * @throws {ProblemDetails} error when the service returns a 413 status code
     */
     put(body: SpaceFieldsDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SpaceFieldsDtoApiOperationResult | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: SpaceFieldsDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const FieldsRequestBuilderUriTemplate = "{+baseurl}/api/spaces/{id}/fields";
/**
 * Metadata for all the requests in the request builder.
 */
export const FieldsRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: FieldsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            413: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSpaceFieldsDtoApiOperationResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSpaceFieldsDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
